name: Main CI/CD Orchestration Pipeline

on:
  push:
    branches:
      - dev # Test deploy on 'dev' branch
      - main # Production deployment trigger
    paths:
      - 'FilesBackend/**'
      - 'LearningGraphFrontend/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'FilesBackend/**'
      - 'LearningGraphFrontend/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/deploy.yml'

jobs:
  test:
    name: Run Tests and Create Artifacts
    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy Application
    needs: test
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'

    uses: ./.github/workflows/deploy.yml
    secrets:
      DEVOPS_SSH_KEY: ${{ secrets.DEVOPS_SSH_KEY }}
      DEVOPS_USERNAME: ${{ secrets.DEVOPS_USERNAME }}
      DEVOPS_PUBLIC_IP: ${{ secrets.DEVOPS_PUBLIC_IP }}